---
- name: Setup ACL information.
  ansible.posix.acl:
    name: "{{ item.name }}"
    default: "{{ item.default | default(omit) }}"
    entity: "{{ item.entity | default(omit) }}"
    entry: "{{ item.entry | default(omit) }}"
    etype: "{{ item.etype | default(omit) }}"
    follow: "{{ item.follow | default(omit) }}"
    permissions: "{{ item.permissions | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    recursive: "{{ item.recursive | default('no') }}"
  loop: "{{ acl_config }}"
  loop_control:
    label: "{{ item.name }}"
